driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.7
    run_list: apt::default
  - name: freebsd-9.3
    run_list: freebsd::portsnap
  - name: freebsd-10.3
    run_list: freebsd::portsnap
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: windows-2012r2-standard
    driver:
      box: chef/windows-server-2012r2-standard # private box in Chef's Atlas account
  - name: windows-2008r2-standard
    driver:
      box: chef/windows-server-2008r2-standard # private box in Chef's Atlas account
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private box in Chef's Atlas account
      provider: vmware_fusion

suites:
- name: resources
  run_list:
  - recipe[test::default]
- name: source
  run_list:
  - recipe[git::source]
  excludes:
    - windows-2012r2-standard
    - windows-2008r2-standard
    - macosx-1011
- name: server
  run_list:
  - recipe[git::server]
  excludes:
    - windows-2012r2-standard
    - windows-2008r2-standard
    - macosx-1011
