name 'angular-universal'
maintainer 'Simian'
maintainer_email 'ivan@simian.co'
license 'all_rights'
description 'Installs/Configures angular-universal'
long_description 'Installs/Configures angular-universal'
version '0.1.0'

depends 'application', '~> 5.0'
depends 'application_git', '~> 1.1.0'
depends 'apt', '~> 5.0.1'
depends 'chef_nginx', '~> 5.0.6'